### PR TITLE
Update blue shark

### PR DESCRIPTION
**Pull request by camrinbraun**
update to blue shark device and deployment metadata and change "raw" language to "decoded sensor data"

### CODE REVIEW

**Comment by camrinbraun** [comment]
Believe this is ready if you guys can take a quick look to confirm it looks right and reflects our discussion

**Comment by jdpye** [comment]
I think the metadata has the organismID, etc. but the RMarkdown needs to be re-run to populate those columns in the L1-4 data products? Is this something you can take on, @camrinbraun ?

**Comment by jdpye** [comment]
Sorry this sat for awhile, a lot of us are working out how to use merge requests for this stuff :)

**Review by peggynewman — APPROVED** [review]
This all looks good to me, do we go ahead and merge? I'm guessing we still need to reknit the Rmd as per @jdpye's comment.

**Comment by camrinbraun** [comment]
should now (https://github.com/ocean-tracking-network/biologging_standardization/commit/1eca3c7c57fd15b1da4cbb1007a3408c07f2e4f5) be re-populated to push the correct metadata throughout the rest of the markdown document and files written out through the process. have another quick look to confirm.

**Review by peggynewman — APPROVED** [review]

**Pull request merged**
